### ISSUE TITLE
Feature request: Video Support

### ISSUE THREAD

**Issue by redaxmedia** [lastguest/pixeler#11]
Hello,

what about video support using [PHP-FFMpeg](https://github.com/PHP-FFMpeg/PHP-FFMpeg)?

```
$video
    ->filters()
    ->extractMultipleFrames(FFMpeg\Filters\Video\ExtractMultipleFramesFilter::FRAMERATE_EVERY_10SEC, '/path/to/destination/folder/')
    ->synchronize();
```

and then loop over the result using the `Pixeler\Canvas`?

**Comment by lastguest** [comment]
Nice, but frame rendering is quite slow (it's userland code, no optimizations) so I don't think it would be useful.
Still, you can obviously write your own library requiring pixeler as a dependency :)
